//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> typeid { get; set; }
        public bool Deleted { get; set; }
    
        public virtual TypeOfDrug TypeOfDrug { get; set; }
    }
}
